### ISSUE TITLE
Telegram Bot Sicherheit

### ISSUE THREAD

**Issue by TBR-BRD** [LukeSkywalker92/TeleFrame#10]
First: Vielen Dank für diese fantastische Arbeit, die Installation ist sehr einfach und es funktioniert einwandfrei.
Ich habe eine Frage zur Sicherheit: im Prinzip kann jeder Bilder an den Bot senden der den Namen kennt? Wenn ja, kann man eventuell ein "Codewort" in die Nachrichtenzeile schreiben die die Anzeige "freischaltet"?

**Comment by LukeSkywalker92** [comment]
Ich glaube, dass du recht hast. Das mit dem Codewort wäre eine Möglichkeit. Eine andere wäre nur bilder von bestimmten User-ID's anzunehmen. Ich bin mir nur noch nicht sicher, was am Ende sicherer und bedienungsfreundlicher ist.

Wenn du jetzt schnell die Sicherheit erhöhen willst, würde ich dir raten, einen schwer erratbaren Botnamen zu verwenden. Also einfach ein paar zufällige Zeichen nehmen.

**Comment by TBR-BRD** [comment]
ok danke für deine Antwort, ich werde das mit dem kryptischen Namen probieren...

**Comment by LukeSkywalker92** [comment]
close with #13
