### ISSUE TITLE
Isn't it time for a new master?

### ISSUE THREAD

**Issue by sohamakl** [LukeSkywalker92/TeleFrame#107]
Isn't it time for a new master? Several of the outstanding issues could be closed.

**Comment by gegu** [comment]
Yeah, but I'm working on a new feature in branch [feature/addon-interface](https://github.com/LukeSkywalker92/TeleFrame/tree/feature/addon-interface). I'd rather wait until the branch is almost finished and has been transferred to develop.

**Comment by sohamakl** [comment]
Can you say something more about it? Addon interface sounds good. Do you have a first addon in mind?

**Comment by gegu** [comment]
Yes, for example a notification LED for new pictures.

I implement this so that, for example, hardware extensions can be implemented without having to change the core. In the end there should not be many limits to the creativity.

I will also provide some examples. Stay tuned, it's coming soon.

**Comment by sohamakl** [comment]
This sounds very intersting. If you like you can close this issue, too.

**Comment by sohamakl** [comment]
I have tested the current develop branch on Rasberry Pi 3 and 4 with Raspberry Pi 7'' DSI and sunfounder 10'' display with opto coupler hardware all with success.

Im running node js 13.7.0, npm 3.13.6 and electron 7.1.10.

Very nice, I'm so happy about this project :-)
