### ISSUE TITLE
startup without internet connection

### ISSUE THREAD

**Issue by Gandalf210** [LukeSkywalker92/TeleFrame#120]
Hey

During the installation, I could select if I want to wait for Internet connectivity before starting teleframe. Is there a way to change it later, after the installation process?

**Comment by LuHKae** [comment]
First remove the old app: pm2 delete TeleFrame
For waiting: pm2 start ~/TeleFrame/tools/pm2_TeleFrame_waitForInternet.json 
For non waiting: pm2 start ~/TeleFrame/tools/pm2_TeleFrame.json
Last save the pm2 config: pm2 save

**Comment by Gandalf210** [comment]
thanks. Works as intended
