### ISSUE TITLE
Toggle Funktion does not work with 7'' touch PI-Display

### ISSUE THREAD

**Issue by webtourhs** [LukeSkywalker92/TeleFrame#123]
Hello,
I have use these parameters in the config.json file
}
.....
 "toggleMonitor": true,
  "turnOnHour": 10,
  "turnOffHour": 20
}
But the Display is always on.
What is the mistake?
Best regards

**Comment by call-me-matt** [comment]
I am using the same screen, the screenoff/screenon works here. Although it seems not to trigger every day.

**Comment by kris711** [comment]
Change existing or add "screenConfig" Parameter in "./config/config.json" to
` "screenConfig": "./config/screens/dsi_raspberry_7inch.js",`

This should help.
