### ISSUE TITLE
config.example.json not copied using installer script

### ISSUE THREAD

**Issue by thoschneider** [LukeSkywalker92/TeleFrame#149]
The readme-file states under configuration:
"Copy TeleFrame/config/config.example.json to TeleFrame/config/config.json. \ **Note**: If you used the installer script. This step is already done for you."
The Note is not true! The installer script creates only the file config.json with one line which contains the token:

_# Create config for start TeleFrame containing the token
echo -e "{\n  \"botToken\": \"$token\"\n}" > config/config.json_

Please remove the note in readme-file and add additional information, that the token must be inserted as value for "botToken". Most convenient would be of course, to alter the installer script in such a way that config.example.json gets copied to config.json and the token is inserted automatically as the token is prompted and stored during installation anyway. Unfortunately I don't feel competent to commit  a solution.

**Comment by LukeSkywalker92** [comment]
closed by #150
