### ISSUE TITLE
Autostart with PM not working

### ISSUE THREAD

**Issue by nielosz** [LukeSkywalker92/TeleFrame#155]
What a *cool* piece of software.

After a fresh install yesterday and updated buster to december version, my raspberry runs into desktop login screen after having started teleframe. Any ideas?

**Comment by LukeSkywalker92** [comment]
Hey,
what is the output for `pm2 status`?

**Comment by nielosz** [comment]
Hey again, after another reboot everything works. I'll try another few times. Thanks a load.
