### ISSUE TITLE
How to modify required settings?

### ISSUE THREAD

**Issue by houch841** [LukeSkywalker92/TeleFrame#168]
Hello,
Great work. I installed on a Raspberry and it works well. I can send photos and they are displayed.
After boot the Teleframe starts automatically and shows the pictures.
But how can I access the configure.js file to change options?

Thanks for your help.
Kind regards.

**Comment by Bigfoot611** [comment]
Does the access via SSH work?
For example (MS Windows): ssh pi@_ip-address-of-your-teleframe_

If yes, you should end up in the users "pi" home directory. Change directory to Teleframe/config and use your preferred editor - e.g. nano - to edit or create "config.json".

**Comment by houch841** [comment]
Thank you. Works well with ssh!
