### ISSUE TITLE
Window Size in main.js

### ISSUE THREAD

**Issue by nautical-miles** [LukeSkywalker92/TeleFrame#31]
Hi,
how important is the window size in main.js? Instead of the 7" screen I am using a 15.6" screen with a resolution of 1366 x 768. Would it make sense to use global variables here and add the size setting to the config?

**Comment by LukeSkywalker92** [comment]
I don't think it matters at all as long as you are running in fullscreen mode. Did you run into any problems?

**Comment by nautical-miles** [comment]
It is running fine. I was just wondering if with this setting the pictures are shown with a lower resolution as possible.

**Comment by LukeSkywalker92** [comment]
No. This just sets the window size of the window when not running in fullscreen. The resolution of the image is not modified.
