### ISSUE TITLE
Picture Freeze

### ISSUE THREAD

**Issue by nautical-miles** [LukeSkywalker92/TeleFrame#38]
Hi,
I create a new issue here as it seems my problem is different to the system freeze issue.
TeleFrame stops randomly on one picture and does not react on touching the screen. However logging on to the raspberry via ssh is possible. Also TeleFrame is turning off the screen at the correct hour when set up in the config. It also turns on the screen the next morning just to see the picture from last night sitting there for hours. Using pm2 restart TeleFrame does not help. Rebooting the raspberry makes TeleFrame work again for some time.

**Comment by LukeSkywalker92** [comment]
did you have a look at the logs?

**Comment by nautical-miles** [comment]
Does TeleFrame have it's own logs or is it stored somewhere else?

**Comment by LukeSkywalker92** [comment]
just type pm2 logs TeleFrame

**Comment by nautical-miles** [comment]
There is an error in the log: Failed to process updates. TelegramError Conflict terminated by other getUpdates Request...
I assume that running two screens with one bot is not working.

**Comment by LukeSkywalker92** [comment]
Ok so we found your problem =) You are right. You need one bot per screen. Telegram does not allow to run multiple instances of one bot.
