### ISSUE TITLE
Nodejs Version 10x wird nicht unterstützt.

### ISSUE THREAD

**Issue by Mai1986** [LukeSkywalker92/TeleFrame#39]
Hallo Luke,

ich habe versucht die automatische Installation für die TeleFrame Software durchzuführen. Leider bekomme ich den Fehler das die Version 10 von Nodejs nicht unterstützt wird. Danach bricht die Installation ab. Nach ein bisschen Stöber habe ich es geschafft die Version 8 von Nodejs installieren. Der Fehler mit der nicht unterstützten Version ist weg. Es konnte dann aber leider nicht das Paket Elektron installiert werden. Ich bin leider echt ratlos aktuell. Liegt auch daran das ich vollkommener Neuling auf GitHub und in Sachen Linux bin. Ich hoffe du kannst mir da weiterhelfen?

VG 
Christian

**Comment by sohamakl** [comment]
Hallo,

mit folgendem Kommando kannst du schauen welche Version von npm installiert installiert ist:

npm -v

Möchtest du sie aktualisieren geht dies wie folgt:

sudo npm install npm@latest -g
sudo reboot

Danach läuft alles wie gewünscht.

**Comment by Mai1986** [comment]
Hallo,

danke erstmal für die Rückmeldung. Mein Problem ist, ich habe die aktuellste Version 10.x........

Beim automatischen installieren der TeleFrame Software bricht der Installer ab weil die Version 10 nicht von dem TeleFrame Paket unterstützt wird. Da komme ich im Moment nicht weiter. 
Besser kann ich es leider nicht beschreiben.

**Comment by LukeSkywalker92** [comment]
Kannst du uns bitte noch ein paar Infos zukommen lassen:
* Welchen Raspberry verwendest du?
* Welches Raspbian hast du installiert?
* Wie bist du bei der Installation genau vorgegangen?

**Comment by Mai1986** [comment]
Ich verwende einen PI 3B+ mit dem System Raspbian Buster Version 10.

Zu erst habe ich den PI für mein Netzwerk konfiguriert.
Danach habe ich mich per SSH eingeloggt. 
Dann habe ich gleich mit dem automatischen Installationspaket begonnen.

Ich habe mal den Terminalverlauf (Falls das hilft) kopiert und als Txt. hinzugefügt.

Ach ja, die Version von NPM ist 5.8.0

Brauchst du noch mehr Infos?
[Terminalverlauf.txt](https://github.com/LukeSkywalker92/TeleFrame/files/3888173/Terminalverlauf.txt)

**Comment by sohamakl** [comment]
Versuch doch mal mit:

```
sudo apt-get update
sudo apt-get upgrade
```
und anschließendem 

```
sudo npm install npm@latest -g
sudo reboot
```

zu aktualisieren. Bei mit funktioniert es auf diese Weise.

**Comment by LukeSkywalker92** [comment]
Funktioniert es mit dem Vorschlag von @sohamakl jetzt?

**Comment by Mai1986** [comment]
Super, vielen vielen vielen Dank!  Es lag an der Version von npm. Nach dem Update auf die neueste Version hat die Installation funktioniert und der TeleFrame läuft :) Ich freu mich echt wie total. Jetzt gibt's doch noch ein Weihnachtsgeschenk für Oma und Opa.

**Comment by LukeSkywalker92** [comment]
Sehr schön. Dann hoffen wir mal, dass das Geschenk gut ankommt :)
