### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by sohamakl** [LukeSkywalker92/TeleFrame#40]
Hi Luke,

how to place suggestions for new features? Is it okay to place it as an issue?

**Comment by LukeSkywalker92** [comment]
Hi,
yes this is the best way in my mind.

**Comment by sohamakl** [comment]
Okay, excellent.

I have two ideas where I'm very interested what you'll say:

- Delete images via touch screen.
- Mark pictures as favorites. These pictures should not be deleted and do not impact the total number of allowed pictures.

**Comment by LukeSkywalker92** [comment]
I think we can close this issue. Details are discussed in #44.
