### ISSUE TITLE
OpenGL fkms problems

### ISSUE THREAD

**Issue by Trenar** [LukeSkywalker92/TeleFrame#75]
Hi all,

I have some problems with the OpenGL acceleration, which is set automatically in the install script. When I enable this option, the whole teleframe software becomes very unresponsive and laggy. Took me a while to find out that it was related to that option. Neither the full kms or fake kms worked for me. 
As a workaround I removed that line from `/boot/config.txt`, however that seems not ideal. If I use a fadetime > 0, I get some very ugly white flickering, which I suspect to vanish with OpenGL working.. 
Is there someone with similar observations? Or can someone tell me what I miss during installation, maybe a gl related package? 

Setup: RPi 3A+ running the latest raspbian buster release.

**Comment by NDscham** [comment]
I am also attempting to set this up on a 3A+ and can confirm the flickering screen between images. I suspect that might also be related to excessive memory consumption and swapping (the 3A+ only has 512MB of RAM). In my case on a fresh raspbian, I am on 100% swap with TeleFrame running.
