### ISSUE TITLE
Only (imageCount-1) images shown

### ISSUE THREAD

**Issue by stefanoco** [LukeSkywalker92/TeleFrame#76]
Could be related [to this line of code](https://github.com/LukeSkywalker92/TeleFrame/blob/62bce5b2c1f5274bce0eee744c43a49cc95338d1/js/imageWatchdog.js#L42) with `>=` instead of `>`

**Comment by Trenar** [comment]
I once found that one too, changed it in #52

**Comment by gegu** [comment]
Fixed in develop
