### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by stefanoco** [LukeSkywalker92/TeleFrame#82]
Having an old tablet hanging around I was asking myself if running TeleFrame on a small host (RPi) and navigating it with a browser from a different networked host (the tablet) is an option. Missing knowledge on Electron etc...

**Comment by Trenar** [comment]
There is a bot-only mode, you could have that one running and sync the images via a cloud service to a folder on your tablet and have a sideshow for that synced folder

**Comment by stefanoco** [comment]
Good idea didn’t come up with this simple solution, thanks!
