### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by LukeSkywalker92** [LukeSkywalker92/TeleFrame#84]
Hey guys,

first of all I want to wish you a merry christmas.
Second, I want to say thank you.
Thank you for the hours you spend to improve this project and to help others with their problems.
Thank you for the nice atmosphere in all the discussions, etc..
Thank you for all bug reports, etc.. All these small things help to improve the software even more.
Special thanks to @gegu, who does a great job in organising contributions and spends a lot of time with writing code for TeleFrame.

I really love to see this project developing, even when my free time is rare at the moment. This confirms my decision to make the project open source. I think we are on the right track to make the TeleFrame an easy to use software for all kinds of people and a beginner friendly project for makers.

Enjoy the Christmas time and have a happy new year!
Luke

**Comment by gegu** [comment]
No need to thank me specifically. I'm glad when I can contribute something. My time won't always allow it in this intensity either. Unfortunately 😄 
It is also a lot of fun. We have a lot of cool new features and also already got a new language.

So the thanks go to the cool project and all who participate.
